### ISSUE TITLE
How to configure User pools and so on?

### ISSUE THREAD

**Issue by hristodd** [thedistance/ra-cognito#1]
Once I install all needed packages, I get an error: "No userPool". I know I should configure this somewhere, but can't find where. Can you please help? The package looks exactly what I need :D

**Comment by TheDistanceHQ** [comment]
The AuthProvider uses the AWS Amplify library. You need to configure AWS Amplify with the details of the User Pool before the AuthProvider gets used. See the AWS Amplify documentation for how to do this. We use environment variables to pass the relevant values into our webpack builds, but you don't have to.

**Comment by hristodd** [comment]
Thank you so much! I will investigate immediately! I'll close the issue.
